version: '3.8'
services:
  web:
    container_name: FastAPI
    build: .
    ports:
      - 2003:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HOST=${HOST}
    volumes:
      - /volume1/docker/cbf_fastapi:/var/lib/cbf_fastapi:rw
    restart: on-failure:5